### ISSUE TITLE
Citations?

### ISSUE THREAD

**Issue by s3i7h** [mogya/encodemax#1]
Qiitaから来ました！

github → デプロイ先
デプロイ先 → github

と移動できないのが不便かなと思いました。とくにgithubには外部の別サイトへのリンクがあるのでさらにわかりづらいかもです!

**Comment by mogya** [comment]
確かに混乱しそうですね。readmeとindexのリンクを変更しておきました。
https://github.com/mogya/encodemax/commit/719c6bceaece9fa24e079b243a7a082b77a26086
https://github.com/mogya/encodemax/commit/9dd26951556abfde37cd188e6b3c5b696ebcb0ee
